// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGiaorQEmpyq-r-OluPwZHaiIZh96lHeI',
    appId: '1:346587036312:web:c5d9f6c7b4e2240e8f6eed',
    messagingSenderId: '346587036312',
    projectId: 'huzur-app-45419',
    authDomain: 'huzur-app-45419.firebaseapp.com',
    storageBucket: 'huzur-app-45419.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKPDZVfsDQES8CqPwBbU3AB0NoYR2Fy6M',
    appId: '1:346587036312:android:3f851485d0ebe9a58f6eed',
    messagingSenderId: '346587036312',
    projectId: 'huzur-app-45419',
    storageBucket: 'huzur-app-45419.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6z9KJ6yO9GND8f3VAJO7Dt5-Rslf-hQU',
    appId: '1:346587036312:ios:3d9efb73d226439e8f6eed',
    messagingSenderId: '346587036312',
    projectId: 'huzur-app-45419',
    storageBucket: 'huzur-app-45419.firebasestorage.app',
    iosBundleId: 'com.example.huzurApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6z9KJ6yO9GND8f3VAJO7Dt5-Rslf-hQU',
    appId: '1:346587036312:ios:3d9efb73d226439e8f6eed',
    messagingSenderId: '346587036312',
    projectId: 'huzur-app-45419',
    storageBucket: 'huzur-app-45419.firebasestorage.app',
    iosBundleId: 'com.example.huzurApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGiaorQEmpyq-r-OluPwZHaiIZh96lHeI',
    appId: '1:346587036312:web:c0bd131d77a579dd8f6eed',
    messagingSenderId: '346587036312',
    projectId: 'huzur-app-45419',
    authDomain: 'huzur-app-45419.firebaseapp.com',
    storageBucket: 'huzur-app-45419.firebasestorage.app',
  );
}
